#!/bin/bash
# Shared defaults and small helpers for the Claude phone monitor scripts.
# shellcheck shell=bash

set -u

CM_LIB_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CM_SCRIPT_DIR="$(CDPATH= cd -- "$CM_LIB_DIR/.." && pwd)"
CM_SKILL_DIR="$(CDPATH= cd -- "$CM_SCRIPT_DIR/.." && pwd)"
CM_REPO_ROOT="$(CDPATH= cd -- "$CM_SKILL_DIR/../.." && pwd)"

CM_VERSION="0.1.0"
CM_HOOK_MARKER="claude-phone-monitor:v1"
CM_LAUNCHD_LABEL="com.claude.phone-monitor"
CM_DEFAULT_EVENTS="SessionStart,UserPromptSubmit,PreToolUse,PostToolUse,PostToolUseFailure,PermissionRequest,Notification,Stop,StopFailure,SessionEnd"
CM_SETTINGS_FILE_DEFAULT="${CLAUDE_PHONE_MONITOR_SETTINGS:-${CLAUDE_CONFIG_DIR:-$HOME/.claude}/settings.json}"
CM_STATE_DIR_DEFAULT="${CLAUDE_PHONE_MONITOR_HOME:-$HOME/.claude-phone-monitor}"
CM_LAUNCH_AGENTS_DIR_DEFAULT="${CLAUDE_PHONE_MONITOR_LAUNCH_AGENTS_DIR:-$HOME/Library/LaunchAgents}"
CM_ADAPTER_DEFAULT="${CLAUDE_PHONE_MONITOR_ADAPTER:-$CM_REPO_ROOT/services/collector/dist/hook-adapter.js}"
CM_NODE_DEFAULT="${CLAUDE_PHONE_MONITOR_NODE:-node}"
CM_PYTHON_DEFAULT="${CLAUDE_PHONE_MONITOR_PYTHON:-python3}"
CM_ENDPOINT_DEFAULT="${CLAUDE_PHONE_MONITOR_ENDPOINT:-http://127.0.0.1:8787/events}"
CM_TEMPLATE="$CM_SKILL_DIR/config/com.claude.phone-monitor.plist.template"

cm_log() {
  printf '[claude-monitor] %s\n' "$*" >&2
}

cm_warn() {
  printf '[claude-monitor] warning: %s\n' "$*" >&2
}

cm_die() {
  printf '[claude-monitor] error: %s\n' "$*" >&2
  exit 1
}

cm_usage_error() {
  cm_die "$* (try --help)"
}

cm_require_command() {
  command -v "$1" >/dev/null 2>&1 || cm_die "required command not found: $1"
}

cm_python() {
  "${CM_PYTHON_DEFAULT}" "$@"
}

cm_abs_path() {
  local path="$1"
  if [ -d "$path" ]; then
    (CDPATH= cd -- "$path" && pwd)
  else
    local dir base
    dir=$(dirname -- "$path")
    base=$(basename -- "$path")
    (CDPATH= cd -- "$dir" 2>/dev/null && printf '%s/%s\n' "$(pwd)" "$base") || printf '%s\n' "$path"
  fi
}

cm_mkdir_state() {
  local state_dir="$1"
  mkdir -p "$state_dir/logs" "$state_dir/run" || cm_die "cannot create state directory: $state_dir"
  chmod 700 "$state_dir" 2>/dev/null || true
}

cm_join_csv() {
  local value="$1"
  printf '%s' "$value" | tr ',' '\n' | awk 'NF { if (out != "") out = out ","; out = out $0 } END { print out }'
}

cm_is_darwin() {
  [ "$(uname -s 2>/dev/null || true)" = "Darwin" ]
}

cm_launchctl_domain() {
  printf 'gui/%s\n' "$(id -u)"
}

cm_load_env() {
  # monitor.env is generated by install and is intentionally a shell fragment.
  # Do not load arbitrary files from user input unless the caller supplied it.
  local state_dir="$1"
  local env_file="$state_dir/monitor.env"
  if [ -f "$env_file" ]; then
    # shellcheck disable=SC1090
    . "$env_file"
  fi
}

cm_render_plist() {
  local output="$1"
  local install_root="$2"
  local state_dir="$3"
  local adapter="$4"
  local node="$5"
  cm_python - "$CM_TEMPLATE" "$output" "$install_root" "$state_dir" "$adapter" "$node" <<'PY'
import html
import os
import pathlib
import sys

template_path, output_path, install_root, state_dir, adapter, node = sys.argv[1:]
text = pathlib.Path(template_path).read_text(encoding="utf-8")
replacements = {
    "__CM_INSTALL_ROOT__": install_root,
    "__CM_STATE_DIR__": state_dir,
    "__CM_ADAPTER__": adapter,
    "__CM_NODE__": node,
}
for key, value in replacements.items():
    text = text.replace(key, html.escape(value, quote=False))
path = pathlib.Path(output_path)
path.parent.mkdir(parents=True, exist_ok=True)
# A launch agent contains no secrets, but remains user-owned and private by default.
tmp = path.with_name(path.name + ".tmp")
tmp.write_text(text, encoding="utf-8")
os.chmod(tmp, 0o600)
os.replace(tmp, path)
PY
}

cm_launchctl_bootout() {
  local plist="$1"
  if ! cm_is_darwin || ! command -v launchctl >/dev/null 2>&1; then
    return 0
  fi
  launchctl bootout "$(cm_launchctl_domain)" "$plist" >/dev/null 2>&1 || true
}

cm_launchctl_bootstrap() {
  local plist="$1"
  if ! cm_is_darwin || ! command -v launchctl >/dev/null 2>&1; then
    cm_log "launchd not loaded (macOS launchctl unavailable; generated plist only)"
    return 0
  fi
  cm_launchctl_bootout "$plist"
  launchctl bootstrap "$(cm_launchctl_domain)" "$plist" >/dev/null 2>&1 || {
    cm_warn "could not load launchd agent; plist was generated at $plist"
    return 0
  }
  launchctl enable "$(cm_launchctl_domain)/$CM_LAUNCHD_LABEL" >/dev/null 2>&1 || true
}

cm_launchctl_unload() {
  local plist="$1"
  if ! cm_is_darwin || ! command -v launchctl >/dev/null 2>&1; then
    return 0
  fi
  cm_launchctl_bootout "$plist"
}
