#!/usr/bin/env bash
# One-command trusted-LAN launcher for the Claude Phone Monitor.
# It starts Relay + Collector in the foreground; Ctrl-C stops processes started here.

set -Eeuo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

ROOT="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${CLAUDE_PHONE_MONITOR_HOME:-$HOME/.claude-phone-monitor}"
PORT="${RELAY_PORT:-8787}"
PAIR=0
INSTALL_HOOKS=0
OPEN_QR=0
WATCH_CODEX="${COLLECTOR_WATCH_CODEX:-0}"
RELAY_PID=""
COLLECTOR_PID=""
RELAY_STARTED=0

usage() {
  cat <<'USAGE'
Usage: start-lan-monitor.sh [options]

Starts the Relay and macOS Collector for the trusted-LAN MVP. The first run
creates a bootstrap secret, creates a one-time pairing, and writes a QR image.

Options:
  --pair            create a fresh one-time pairing QR
  --install-hooks   merge monitor-owned Claude Code Hooks (real settings change)
  --watch-codex     read local Codex session JSONL and send safe lifecycle metadata
  --no-watch-codex  disable Codex watching even when COLLECTOR_WATCH_CODEX=1
  --open-qr         open pairing.png in Preview after pairing
  --no-build        do not build relay/collector before starting
  -h, --help        show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pair) PAIR=1; shift ;;
    --install-hooks) INSTALL_HOOKS=1; shift ;;
    --watch-codex) WATCH_CODEX=1; shift ;;
    --no-watch-codex) WATCH_CODEX=0; shift ;;
    --open-qr) OPEN_QR=1; shift ;;
    --no-build) NO_BUILD=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

NO_BUILD="${NO_BUILD:-0}"
mkdir -p "$STATE_DIR/logs" "$STATE_DIR/run"
chmod 700 "$STATE_DIR" 2>/dev/null || true

# Reuse an existing generated env file so the Relay secret remains stable.
if [[ -f "$STATE_DIR/monitor.env" ]]; then
  # This file is generated by the pairing helper with shell-quoted values.
  # shellcheck disable=SC1090
  source "$STATE_DIR/monitor.env"
fi

BOOTSTRAP_SECRET="${RELAY_BOOTSTRAP_SECRET:-}"
if [[ -z "$BOOTSTRAP_SECRET" ]]; then
  SECRET_FILE="$STATE_DIR/bootstrap.secret"
  if [[ -s "$SECRET_FILE" ]]; then
    BOOTSTRAP_SECRET="$(<"$SECRET_FILE")"
  else
    BOOTSTRAP_SECRET="$(openssl rand -hex 32)"
    printf '%s\n' "$BOOTSTRAP_SECRET" > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE"
  fi
fi

LAN_IP="${RELAY_LAN_IP:-}"
if [[ -z "$LAN_IP" ]]; then
  for interface in en1 en0; do
    LAN_IP="$(ipconfig getifaddr "$interface" 2>/dev/null || true)"
    [[ -n "$LAN_IP" ]] && break
  done
fi
[[ -n "$LAN_IP" ]] || { printf 'Could not determine Mac LAN address. Set RELAY_LAN_IP.\n' >&2; exit 1; }

PUBLIC_URL="${RELAY_PUBLIC_URL:-http://$LAN_IP:$PORT}"
DB_PATH="${RELAY_DB_PATH:-$STATE_DIR/relay.sqlite}"
RELAY_HTTP_LOCAL="http://127.0.0.1:$PORT"
RELAY_WS_LAN="ws://$LAN_IP:$PORT/ws/collector"

cleanup() {
  local status=$?
  if [[ -n "$COLLECTOR_PID" ]] && kill -0 "$COLLECTOR_PID" 2>/dev/null; then
    kill "$COLLECTOR_PID" 2>/dev/null || true
  fi
  if [[ "$RELAY_STARTED" -eq 1 && -n "$RELAY_PID" ]] && kill -0 "$RELAY_PID" 2>/dev/null; then
    kill "$RELAY_PID" 2>/dev/null || true
  fi
  wait 2>/dev/null || true
  exit "$status"
}
trap cleanup INT TERM EXIT

if [[ "$NO_BUILD" -eq 0 ]]; then
  npm --prefix "$ROOT/services/relay" run build
  npm --prefix "$ROOT/services/collector" run build
fi

if ! curl --fail --silent --max-time 2 "$RELAY_HTTP_LOCAL/healthz" >/dev/null 2>&1; then
  (
    RELAY_HOST=0.0.0.0 \
    RELAY_PORT="$PORT" \
    RELAY_PUBLIC_URL="$PUBLIC_URL" \
    RELAY_BOOTSTRAP_SECRET="$BOOTSTRAP_SECRET" \
    RELAY_DB_PATH="$DB_PATH" \
    npm --prefix "$ROOT/services/relay" run start
  ) >> "$STATE_DIR/logs/relay.log" 2>&1 &
  RELAY_PID=$!
  RELAY_STARTED=1
  for _ in {1..30}; do
    curl --fail --silent --max-time 1 "$RELAY_HTTP_LOCAL/healthz" >/dev/null 2>&1 && break
    sleep 1
  done
fi
curl --fail --silent --max-time 2 "$RELAY_HTTP_LOCAL/healthz" >/dev/null 2>&1 || {
  printf 'Relay did not become healthy. See %s/logs/relay.log\n' "$STATE_DIR" >&2
  exit 1
}

if [[ "$PAIR" -eq 1 || ! -s "$STATE_DIR/monitor.env" || -z "${COLLECTOR_RELAY_TOKEN:-}" ]]; then
  RELAY_BOOTSTRAP_SECRET="$BOOTSTRAP_SECRET" \
    "$ROOT/skills/claude-monitor/scripts/pair" \
    --relay-http "$RELAY_HTTP_LOCAL" \
    --relay-ws "$RELAY_WS_LAN" \
    --public-url "$PUBLIC_URL"
  # shellcheck disable=SC1090
  source "$STATE_DIR/monitor.env"
fi

COLLECTOR_RELAY_URL="${COLLECTOR_RELAY_URL:-$RELAY_WS_LAN}"
COLLECTOR_RELAY_TOKEN="${COLLECTOR_RELAY_TOKEN:-}"
COLLECTOR_INSTALLATION_ID="${COLLECTOR_INSTALLATION_ID:-}"
[[ -n "$COLLECTOR_RELAY_TOKEN" && -n "$COLLECTOR_INSTALLATION_ID" ]] || {
  printf 'Pairing is incomplete; run with --pair.\n' >&2
  exit 1
}

if [[ "$INSTALL_HOOKS" -eq 1 ]]; then
  "$ROOT/skills/claude-monitor/scripts/install" --no-launchd --no-load
fi

COLLECTOR_ARGS=(--collector)
if [[ "$WATCH_CODEX" == "1" ]]; then
  COLLECTOR_ARGS+=(--watch-codex)
fi

COLLECTOR_RELAY_URL="$COLLECTOR_RELAY_URL" \
COLLECTOR_RELAY_TOKEN="$COLLECTOR_RELAY_TOKEN" \
COLLECTOR_INSTALLATION_ID="$COLLECTOR_INSTALLATION_ID" \
  COLLECTOR_WATCH_CODEX="$WATCH_CODEX" \
  COLLECTOR_DATA_DIR="${COLLECTOR_DATA_DIR:-$STATE_DIR}" \
  COLLECTOR_SOCKET_PATH="${COLLECTOR_SOCKET_PATH:-$STATE_DIR/collector.sock}" \
  npm --prefix "$ROOT/services/collector" run start -- "${COLLECTOR_ARGS[@]}" \
  >> "$STATE_DIR/logs/collector.log" 2>&1 &
COLLECTOR_PID=$!

if [[ "$OPEN_QR" -eq 1 && -f "$STATE_DIR/pairing.png" ]]; then
  open "$STATE_DIR/pairing.png" >/dev/null 2>&1 || true
fi

printf '\nClaude Phone Monitor is running on the trusted LAN.\n'
printf 'Relay: %s\n' "$PUBLIC_URL"
printf 'Pairing QR: %s/pairing.png\n' "$STATE_DIR"
printf 'Collector log: %s/logs/collector.log\n' "$STATE_DIR"
if [[ "$WATCH_CODEX" == "1" ]]; then
  printf 'Codex session monitoring: enabled (read-only; no Codex config or hooks changed)\n'
else
  printf 'Codex session monitoring: disabled\n'
fi
printf 'Press Ctrl-C to stop processes started by this script.\n\n'
wait "$COLLECTOR_PID"
